name: WiredBrain-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore WiredBrain.CustomerPortal.AspNet.sln
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.16.3
    
    - name: Restore npm packages
      run: npm install
      working-directory: ./WiredBrain.CustomerPortal.AspNet
   
    - name: npm Security Audit
      run: npm audit --audit-level=high
      working-directory: ./WiredBrain.CustomerPortal.AspNet
          
    - name: Build and Publish Web App
      run: msbuild WiredBrain.CustomerPortal.AspNet.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: WiredBrain.CustomerPortal.AspNet\bin\Release\Publish
